language: python
script: 
        - coverage run parser_test.py
        - coverage run parser_unit_tests.py
        - coverage run -m pytest test_config_data.py
        - coverage combine
after_success:
        - codecov
