language: python
script: 
        - coverage run parser_test.py
        - coverage run -a parser_unit_tests.py
        - coverage run -a -m pytest test_config_data.py
after_success:
        - codecov
